September newsletter
maplibre/maplibre.github.io pull request #243
Opened 2023-09-20 14:29 UTC by wipfli

Template for the September newsletter. 

@HarelM and @louwers please add a few words about web and native. Thanks!

2023-09-21 19:57 UTC, louwers requested changes
We should not put images in the git repo.

2023-09-21 22:29 UTC, nyurik commented
@louwers why not?  If the image is small enough, i don't see any reason to keep it text-only

2023-09-23 20:22 UTC, HarelM commented on content/news/2023-09-18-maplibre-newsletter-september-2023/index.md
> +## MapLibre GL JS
```suggestion
## MapLibre GL JS

We've released version 3.3.1 with a few minor bug fixes related to typings and improved license.txt file handling for packaging tools.

```

2023-09-23 20:23 UTC, HarelM commented
I've updated web with minimal text as there wasn't a lot to update...

2023-09-23 20:43 UTC, louwers commented
@nyurik Because it will balloon the git repo over time. And git doesn't deal well with binary files. For example, you delete one it will still be part of the git history, and it's a pain to scrum them.

There is also a 1GB GitHub Pages size limit, which we will hit pretty quickly if we make a habit of storing binary blobs on GitHub pages.

There is also a 100 GB bandwidth limit, which sounds like quite a lot, but hitting the front page of Hacker News brings 10k-30k visitors to the site *per day*, so we'd likely hit the limit in that case (although Cloudflare caching may make this a non-issue).

2023-09-25 17:29 UTC, HarelM approved these changes

2023-09-26 08:46 UTC, louwers approved these changes

2023-09-26 17:39 UTC, merged

2023-09-26 17:40 UTC, wipfli commented
@tordans did you get a RSS notification for this newsletter now?

2023-09-26 18:19 UTC, tordans commented
@wipfli yes, looks great. Thanks for getting this deployed!
Will look into providing the full feed when I find time…

<img width="1123" alt="image" src="https://github.com/maplibre/maplibre.github.io/assets/111561/f3051e25-d63c-4840-a2da-c980eb9a0849">

2023-09-26 18:26 UTC, wipfli commented
Oh nice, well, thanks for setting it up!