Add Projects
maplibre/maplibre.github.io pull request #30
Opened 2022-05-07 16:03 UTC by maxammann

2022-05-07 16:08 UTC, maxammann commented
I'm a little bit confused by the MapTiler documentation which is referenced as third party integrations. Is that the current documenation for android/ios?

2022-05-07 16:48 UTC, wipfli commented
MapLibre has no docs for native as far as I know. @roblabs @ntadej @birkskyum correct me if I am wrong...

2022-05-07 18:24 UTC, maxammann commented
> MapLibre has no docs for native as far as I know. @roblabs @ntadej @birkskyum correct me if I am wrong...

In that case I would just link the MapTiler documentation as offical.

2022-05-13 04:55 UTC, wipfli requested changes
Hi Max. Looks nice, thanks. Please fix the geocoder-directions stuff, otherwise it looks good to me.

2022-05-13 04:55 UTC, wipfli commented on content/projects/maplibre-gl-geocoder/index.md
> +A plugin to show routing directions on a MapLibre GL JS map
I think it is just a geocoder.

2022-05-13 04:55 UTC, wipfli commented on content/projects/maplibre-gl-directions/index.md
> +Geocoding for MapLibre GL JS
Should be directions..

2022-05-13 04:55 UTC, wipfli commented on content/projects/maplibre-gl-directions/index.md
> +Geocoding for MapLibre GL JS
Should be directions..

2022-05-13 08:13 UTC, maxammann commented
Thanks for catching this! Should be fine now :)

2022-05-13 10:11 UTC, wipfli approved these changes

2022-05-13 10:11 UTC, merged