chore: resolve deprecation around `data.GetJSON`
maplibre/maplibre.github.io pull request #354
Opened 2024-11-16 23:19 UTC by CommanderStorm

This PR removes this deprecation warning:
![image](https://github.com/user-attachments/assets/d04ef2f7-fdb9-4d83-a761-232a52a7155d)

proof that this still works:
![image](https://github.com/user-attachments/assets/62c2a6b0-afb4-42b6-bd49-0cd74c74f1e8)

2024-11-16 23:22 UTC, CommanderStorm commented on layouts/shortcodes/charter.html
> +{{ $cacheKey := print $url (now.Format "2006-01-02") }}
why I added this: https://gohugo.io/functions/resources/getremote/#caching

Given that the site is build in CI might not be a real issue, but (if the charter gets changed in the future) might prevent dev-confusion why this is not updated..

2024-11-17 06:12 UTC, HarelM commented
I'll be happy to approve this, but I'm not sure I fully understand everything I read...
Cc: @ramyaragupathy @louwers

2024-11-17 13:08 UTC, louwers commented
Honestly this whole approach seems overcomplicated to me.

2024-11-17 13:31 UTC, louwers requested changes
This shortcode and the /charter page should be removed.

We link directly to the version on GitHub now. https://maplibre.org/about/

2024-11-17 14:21 UTC, louwers approved these changes

2024-11-17 14:22 UTC, louwers commented
Thank you. 🙏

2024-11-17 14:22 UTC, merged